#include "gpio.h"

void GPIO_Init(void){
	RCC->IOPENR   |= RCC_IOPENR_GPIOBEN | RCC_IOPENR_GPIOCEN|RCC_IOPENR_GPIOAEN;

	GPIOA->MODER  &= ~(GPIO_MODER_MODE0_Msk);
	GPIOA->MODER  |= OUTPUT_MODE << GPIO_MODER_MODE0_Pos;	//PA0 Led D1
}
